import * as lightColors from "./light";

export const Colors = {
  ...lightColors.amber,
  ...lightColors.blue,
  ...lightColors.bronze,
  ...lightColors.brown,
  ...lightColors.crimson,
  ...lightColors.cyan,
  ...lightColors.gold,
  ...lightColors.grass,
  ...lightColors.gray,
  ...lightColors.green,
  ...lightColors.indigo,
  ...lightColors.lime,
  ...lightColors.mauve,
  ...lightColors.mint,
  ...lightColors.olive,
  ...lightColors.orange,
  ...lightColors.pink,
  ...lightColors.plum,
  ...lightColors.purple,
  ...lightColors.red,
  ...lightColors.sage,
  ...lightColors.sand,
  ...lightColors.sky,
  ...lightColors.slate,
  ...lightColors.teal,
  ...lightColors.tomato,
  ...lightColors.violet,
  ...lightColors.yellow,
} as const;
