export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { QueryProvider } from '@lib'
import { ThemeProvider } from '@styles'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <QueryProvider>
        <ThemeProvider>{children}</ThemeProvider>
      </QueryProvider>
    </html>
  )
}
