export const bgBlend = {
	normal: "background-blend-normal",
	multiply: "background-blend-multiply",
	screen: "background-blend-screen",
	overlay: "background-blend-overlay",
	darken: "background-blend-darken",
	lighten: "background-blend-lighten",
	"color-dodge": "background-blend-color-dodge",
	"color-burn": "background-blend-color-burn",
	"hard-light": "background-blend-hard-light",
	"soft-light": "background-blend-soft-light",
	difference: "background-blend-difference",
	exclusion: "background-blend-exclusion",
	hue: "background-blend-hue",
	saturation: "background-blend-saturation",
	color: "background-blend-color",
	luminosity: "background-blend-luminosity",
	"plus-lighter": "background-blend-plus-lighter",
}
