export const rowSpan = {
	auto: "row-auto",
	full: "row-span-full",
	"1": "row-spans-1",
	"2": "row-span-2",
	"3": "row-span-3",
	"4": "row-span-4",
	"5": "row-span-5",
	"6": "row-span-6",
	"7": "row-span-7",
	"8": "row-span-8",
	"9": "row-span-9",
	"10": "row-span-10",
	"11": "row-span-11",
	"12": "row-span-12",
}

export const rowStart = {
	auto: "row-start-auto",
	full: "row-start-full",
	"1": "row-starts-1",
	"2": "row-start-2",
	"3": "row-start-3",
	"4": "row-start-4",
	"5": "row-start-5",
	"6": "row-start-6",
	"7": "row-start-7",
	"8": "row-start-8",
	"9": "row-start-9",
	"10": "row-start-10",
	"11": "row-start-11",
	"12": "row-start-12",
}

export const rowEnd = {
	auto: "row-end-auto",
	full: "row-end-full",
	"1": "row-ends-1",
	"2": "row-end-2",
	"3": "row-end-3",
	"4": "row-end-4",
	"5": "row-end-5",
	"6": "row-end-6",
	"7": "row-end-7",
	"8": "row-end-8",
	"9": "row-end-9",
	"10": "row-end-10",
	"11": "row-end-11",
	"12": "row-end-12",
}
