export const opacity = {
	"0": "opacity-0",
	"5": "opacity-5",
	"10": "opacity-10",
	"20": "opacity-20",
	"25": "opacity-25",
	"30": "opacity-30",
	"40": "opacity-40",
	"50": "opacity-50",
	"60": "opacity-60",
	"70": "opacity-70",
	"75": "opacity-75",
	"80": "opacity-80",
	"90": "opacity-90",
	"100": "opacity-100",
}

export const mixBlend = {
	normal: "mix-blend-normal",
	multiply: "mix-blend-multiply",
	screen: "mix-blend-screen",
	overlay: "mix-blend-overlay",
	darken: "mix-blend-darken",
	lighten: "mix-blend-lighten",
	"color-dodge": "mix-blend-color-dodge",
	"color-burn": "mix-blend-color-burn",
	"hard-light": "mix-blend-hard-light",
	"soft-light": "mix-blend-soft-light",
	difference: "mix-blend-difference",
	exclusion: "mix-blend-exclusion",
	hue: "mix-blend-hue",
	saturation: "mix-blend-saturation",
	color: "mix-blend-color",
	luminosity: "mix-blend-luminosity",
	"plus-lighter": "mix-blend-plus-lighter",
}

export const bgBlend = {
	normal: "background-blend-normal",
	multiply: "background-blend-multiply",
	screen: "background-blend-screen",
	overlay: "background-blend-overlay",
	darken: "background-blend-darken",
	lighten: "background-blend-lighten",
	"color-dodge": "background-blend-color-dodge",
	"color-burn": "background-blend-color-burn",
	"hard-light": "background-blend-hard-light",
	"soft-light": "background-blend-soft-light",
	difference: "background-blend-difference",
	exclusion: "background-blend-exclusion",
	hue: "background-blend-hue",
	saturation: "background-blend-saturation",
	color: "background-blend-color",
	luminosity: "background-blend-luminosity",
	"plus-lighter": "background-blend-plus-lighter",
}
