import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'
import { Sidebar } from '@/components/primitives/sidebar'
import { BibleSide } from './bible/components/bible-side'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
  }>
) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'p-sm')}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Sidebar>
            <BibleSide />
            <div className="py-xs">{props.children}</div>
          </Sidebar>
        </ThemeProvider>
      </body>
    </html>
  )
}
