import * as colors from "./dark";

export const DarkColors = {
  ...colors.amberDark,
  ...colors.blueDark,
  ...colors.bronzeDark,
  ...colors.brownDark,
  ...colors.crimsonDark,
  ...colors.cyanDark,
  ...colors.goldDark,
  ...colors.grassDark,
  ...colors.grayDark,
  ...colors.greenDark,
  ...colors.indigoDark,
  ...colors.limeDark,
  ...colors.mauveDark,
  ...colors.mintDark,
  ...colors.oliveDark,
  ...colors.orangeDark,
  ...colors.pinkDark,
  ...colors.plumDark,
  ...colors.purpleDark,
  ...colors.redDark,
  ...colors.sageDark,
  ...colors.sandDark,
  ...colors.skyDark,
  ...colors.slateDark,
  ...colors.tealDark,
  ...colors.tomatoDark,
  ...colors.violetDark,
  ...colors.yellowDark,
} as const;
