import * as colors from "./light";

export const LightColors = {
  ...{ white: "#fff" },
  ...{ black: "#000" },
  ...colors.amber,
  ...colors.blue,
  ...colors.bronze,
  ...colors.brown,
  ...colors.crimson,
  ...colors.cyan,
  ...colors.gold,
  ...colors.grass,
  ...colors.gray,
  ...colors.green,
  ...colors.indigo,
  ...colors.lime,
  ...colors.mauve,
  ...colors.mint,
  ...colors.olive,
  ...colors.orange,
  ...colors.pink,
  ...colors.plum,
  ...colors.purple,
  ...colors.red,
  ...colors.sage,
  ...colors.sand,
  ...colors.sky,
  ...colors.slate,
  ...colors.teal,
  ...colors.tomato,
  ...colors.violet,
  ...colors.yellow,
} as const;
