name: "publish package to npm"

on: push

jobs:
  publish:
    if: contains(github.event.head_commit.message, '[npm]')
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: publish
        run: |
          cd packages/cli
          npm publish --access public
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
