name: "publish package to npm"

on:
  workflow_run:
    workflows: ["Check commit message"]
    types:
      - completed

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.PUBLISH_NPM == 'true'
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: publish
        run: |
          cd packages/cli
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
